import {
  AlignLeft,
  Award,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  BedDouble,
  BookOpenCheck,
  Briefcase,
  Building2,
  ChartNoAxesColumn,
  CheckCircle2,
  Cog,
  Cpu,
  Crown,
  Crosshair,
  Download,
  Gauge,
  Gift,
  Globe,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  IdCard,
  IndianRupee,
  Info,
  Laptop,
  Layers,
  Lightbulb,
  LineChart,
  ListChecks,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Pause,
  Percent,
  Phone,
  PieChart,
  Play,
  Quote,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  Smile,
  Sparkles,
  Sun,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  UsersRound,
  Wallet,
  Wallet2,
  Expand,
  Eye,
  Flag,
  Zap
} from "lucide-react";

export const investIcons = {
  users: Users,
  percent: Percent,
  monitorSmartphone: MonitorSmartphone,
  barChart: BarChart3,
  building: Building2,
  trendingUp: TrendingUp,
  lineChart: LineChart,
  wallet: Wallet,
  rocket: Rocket,
  monitor: Monitor,
  layers: Layers,
  passive: BedDouble,
  badge: BadgeCheck,
  expand: Expand,
  chart: ChartNoAxesColumn,
  sparkles: Sparkles,
  handshake: Handshake,
  cog: Cog,
  trophy: Trophy,
  listChecks: ListChecks,
  id: IdCard,
  banknote: Banknote,
  wallet2: Wallet2,
  gift: Gift,
  download: Download,
  timer: Timer,
  cpu: Cpu,
  crosshair: Crosshair,
  rupee: IndianRupee,
  gauge: Gauge,
  mapPin: MapPin,
  pieChart: PieChart,
  info: Info,
  play: Play,
  pause: Pause,
  search: Search,
  crown: Crown,
  checkCircle: CheckCircle2,
  shieldCheck: ShieldCheck,
  message: MessageCircle,
  messageSquare: MessageSquare,
  award: Award,
  badgeDollar: BadgeDollarSign,
  laptop: Laptop,
  bookOpenCheck: BookOpenCheck,
  heartPulse: HeartPulse,
  sun: Sun,
  heart: Heart,
  heartHandshake: HeartHandshake,
  quote: Quote,
  flag: Flag,
  usersRound: UsersRound,
  monitorPlay: MonitorPlay,
  globe: Globe,
  mail: Mail,
  send: Send,
  phone: Phone,
  alignLeft: AlignLeft,
  briefcase: Briefcase,
  headphones: Headphones,
  zap: Zap
} as const;

export type IconKey = keyof typeof investIcons;

export const getInvestIcon = (name: IconKey) => investIcons[name] ?? Sparkles;
